Adding support for named graphs
rdfhdt/hdt-java pull request #196
Opened 2023-05-31 09:19 UTC by QuentinJanuel

This pull request will aim to address the issue #3

2023-07-18 03:09 UTC, bb010g commented
Is this based on [HDTQ](<https://doi.org/10.1007/978-3-319-93417-4_13>) (previous implementation: <https://github.com/Rummy23/hdtq-java>)?

2023-07-19 14:52 UTC, QuentinJanuel commented
@bb010g Yes

2023-08-16 14:24 UTC, ate47 requested changes
The code is fine, I added some comments.

Adding some tests in the core would be better to make this new part reliable.

2023-08-28 10:45 UTC, QuentinJanuel commented on hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/bitmap/Bitmap64Roaring.java
> +		b1.putLong(size);
I am not sure myself, I first provided my own implementation of Bitmap for RoaringBitmaps, but while I was debugging some weird bugs I moved to the hdtq-java implementation to see if the problem came from there.

2023-08-28 10:47 UTC, QuentinJanuel commented on hdt-java-cli/src/main/java/org/rdfhdt/hdt/tools/HdtSearch.java
> +		ParserException ex = new ParserException(
Fixed with [cbfeedc27d0d5b5a79b2be40b204827e43832e2e](https://github.com/rdfhdt/hdt-java/commit/cbfeedc27d0d5b5a79b2be40b204827e43832e2e)

2023-08-28 10:48 UTC, QuentinJanuel commented on hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/bitmap/Bitmap64Roaring.java
> +		return HDTVocabulary.BITMAP_TYPE_PLAIN;
fixed with [fef55fbc41d952158b0e057a29f832eddbce7536](https://github.com/rdfhdt/hdt-java/commit/fef55fbc41d952158b0e057a29f832eddbce7536) and [523366358246cf92a0a7537822e7c39272baea65](https://github.com/rdfhdt/hdt-java/commit/523366358246cf92a0a7537822e7c39272baea65)

2023-08-28 10:49 UTC, QuentinJanuel commented on hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/bitmap/Bitmap64Roaring.java
> +	public void append(boolean value) { }
Fixed with [59bba7cf10f4c1c5af2c31188e9087acfa75707e](https://github.com/rdfhdt/hdt-java/commit/59bba7cf10f4c1c5af2c31188e9087acfa75707e)

2023-08-28 10:51 UTC, QuentinJanuel commented on hdt-api/src/main/java/org/rdfhdt/hdt/triples/TripleID.java
> +		return subject == -1 || predicate == -1 || object == -1 || graph == -1;
I am not sure because iirc the graph field is 0 (uninitiated) when this is not a graph, but just in case (like if we manually set it to not be a graph anymore), fixed with [7ae491cb893134dcae943088860d42b97af1094f](https://github.com/rdfhdt/hdt-java/commit/7ae491cb893134dcae943088860d42b97af1094f)

2023-08-28 10:54 UTC, QuentinJanuel commented on hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/impl/BitmapTriplesIteratorYFOQ.java
> +	public final long predBase;
Even private is possible, fixed with [eacd5bb6a63750404970427c28edcf041c4721a8](https://github.com/rdfhdt/hdt-java/commit/eacd5bb6a63750404970427c28edcf041c4721a8)
I forgot to put them back as private after some debugging
Still I couldn't make the field "posZ" public, not protected, because it is needed in a composition pattern. The best I could do is create a getter(& setter?)

2023-08-28 11:02 UTC, QuentinJanuel commented on hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/impl/BitmapTriples.java
> +	public AdjacencyList adjY, adjZ, adjIndex;
Yes, the class BitmapTriples is used by, for instance, BitmapQuadsIteratorZFOQ which needs to read these fields. This is done with a composition pattern, not inheritance, so protected won't work. The best I could to is creating getters (and setters maybe? didn't check if needed)

2023-08-28 11:08 UTC, QuentinJanuel commented on hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/impl/BitmapQuadTriples.java
> +	public List<Bitmap> getQuadInfoAG() {
I wasn't worried about the safety of the cast, but with covariance: since we return a mutable reference to the list with a supertype (Bitmap) of the actual valid values (ModifiableBitmap), then someone would be allowed to insert a non modifiable bitmap in the list, leading to undefined behaviors. AFAIK, the only safe way to deal with that is to clone the list (not deeply) before exposing it.

Also your solution doesn't work on my end anyway, because it can't coerce from List<? extends Bitmap> to List<Bitmap>

2023-08-31 08:46 UTC, ate47 commented on hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/impl/BitmapQuadTriples.java
> +	public List<Bitmap> getQuadInfoAG() {
Just replace your `List<Bitmap>` to `List<? extends Bitmap>` in BitmapTriples, BitmapQuadsIterator and BitmapQuadsIteratorYFOQ and it'll work.

2023-08-31 15:58 UTC, QuentinJanuel commented on hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/impl/BitmapQuadTriples.java
> +	public List<Bitmap> getQuadInfoAG() {
Fixed with [f61bc5826b9d1460d31a0773ff0bee75e1ae6419](https://github.com/rdfhdt/hdt-java/commit/f61bc5826b9d1460d31a0773ff0bee75e1ae6419)

2023-09-05 09:29 UTC, D063520 commented
Hi Quintin, I saw that you added named graph cat test. This is fine, but what we would need more is the following:

- index one hdt
- run all different types of iterators and check if the result is the right one

this is the main test we need. You can ping me if it is not clear ...

2023-09-05 09:54 UTC, QuentinJanuel commented
Sure no problem, I will prioritize these tests then

2023-09-14 08:52 UTC, merged

2023-09-14 08:52 UTC, D063520 commented
thank you for the contribution and the reviews!